CREATE DATABASE TaskManagerTest; 
USE TaskManagerTest; 

CREATE TABLE Role(
	Id INT NOT NULL IDENTITY PRIMARY KEY,
	Description VARCHAR(255) NOT NULL, 
	IsActive BIT
);

CREATE TABLE Profile(
	Id INT NOT NULL IDENTITY PRIMARY KEY, 
	Name VARCHAR(255) NOT NULL, 
	Email VARCHAR(255) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	RoleId INT FOREIGN KEY REFERENCES Role(Id),
	IsActive BIT
);

CREATE TABLE Task(
	Id INT NOT NULL IDENTITY PRIMARY KEY, 
	Description VARCHAR(500) NOT NULL, 
	Status INT NOT NULL, 
	Date DATETIME NOT NULL, 
	IsActive BIT, 
	SponsorId INT FOREIGN KEY REFERENCES Profile(Id)
)

CREATE TABLE TaskDependency(
	TaskId INT FOREIGN KEY REFERENCES Task(Id),
	PendingTask INT FOREIGN KEY REFERENCES Task(Id)
)
